sudo: required

language: bash

services:
  - docker

env:
  global:
    - SONARQUBE_VERSION="lts"
    - MYSQL_VERSION="5.7"
    - COMPOSE_FILE="$TRAVIS_BUILD_DIR/SonarOnDocker/docker-compose-mysql.yml"

git:
  depth: 1

install:
  - git clone --branch=$TRAVIS_BRANCH https://github.com/thyrlian/SonarOnDocker.git

script:
  - docker pull sonarqube:$SONARQUBE_VERSION
  - docker pull mysql:$MYSQL_VERSION
  - sed -i "s/image\:\ sonarqube/image\:\ sonarqube\:$SONARQUBE_VERSION/g" $COMPOSE_FILE
  - sed -i "s/image\:\ mysql/image\:\ mysql\:$MYSQL_VERSION/g" $COMPOSE_FILE
  - docker-compose -f $COMPOSE_FILE run --service-ports -d sonarqube
  - for ((i=1; i<=300; i++)) { sleep 1; if docker ps -aqf "ancestor=mysql:$MYSQL_VERSION" | xargs docker logs 2>&1 | grep "ready for connections" &> /dev/null && docker ps -aqf "ancestor=sonarqube:$SONARQUBE_VERSION" | xargs docker logs 2>&1 | grep "SonarQube is up" &> /dev/null; then return 0; fi } && return 1
  - curl -s -w "%{http_code}\\n" "http://localhost:9000/" -o /dev/null | grep "200\|302" &> /dev/null

after_success:
  - echo "☑☑☑☑☑☑☑☑☑☑☑☑☑☑☑☑☑☑☑☑☑☑☑☑☑☑☑☑☑☑☑☑☑☑☑☑☑☑☑☑☑☑☑☑☑☑☑☑☑☑☑☑☑"
  - echo "---------- Docker orchestration succeeded! ----------"
  - echo "☑☑☑☑☑☑☑☑☑☑☑☑☑☑☑☑☑☑☑☑☑☑☑☑☑☑☑☑☑☑☑☑☑☑☑☑☑☑☑☑☑☑☑☑☑☑☑☑☑☑☑☑☑"

after_failure:
  - echo "☒☒☒☒☒☒☒☒☒☒☒☒☒☒☒☒☒☒☒☒☒☒☒☒☒☒☒☒☒☒☒☒☒☒☒☒☒☒☒☒☒☒☒☒☒☒☒☒☒☒"
  - echo "---------- Docker orchestration failed! ----------"
  - echo "☒☒☒☒☒☒☒☒☒☒☒☒☒☒☒☒☒☒☒☒☒☒☒☒☒☒☒☒☒☒☒☒☒☒☒☒☒☒☒☒☒☒☒☒☒☒☒☒☒☒"

after_script:
  - echo "---------- MySQL logs ----------"
  - echo "=================================================="
  - docker ps -aqf "ancestor=mysql:$MYSQL_VERSION" | xargs docker logs 2>&1
  - echo "=================================================="
  - echo "---------- SonarQube logs ----------"
  - echo "=================================================="
  - docker ps -aqf "ancestor=sonarqube:$SONARQUBE_VERSION" | xargs docker logs 2>&1
  - echo "=================================================="
